module.exports = {
  originEventNumber: 'NumOcorrencia',
  eventInitialDate: 'DtInicio',
  eventFinalDate: 'DtFim',
  eventCity: 'AgMun',
  eventState: 'AgUF',
  eventValue: 'VlCred',
  notifierId: 'CPFCNPJCom',
  eventDescription: 'Det',
  eventLegalContextAppliedContainer: 'ENQUADRAMENTOS',
  eventLegalContextApplied: 'CodEnq',
  eventAssociatedPeopleContainer: 'ENVOLVIDOS',
  eventAssociatedPeople: 'ENVOLVIDO',
  personQualification: 'TpEnv',
  personIsPoliticallyExposed: 'PEP',
  personIsObliged: 'PObrigada',
  personIsGovernmentEmployee: 'ServPub',
  personName: 'NmEnv',
  personId: 'CPFCNPJEnv',
}
